#!/bin/bash
# ============================================================
# Qji 奏在 — Audio Loopback Setup
#  - Persist snd-aloop (ALSA loopback)
#  - Detect connected USB DAC and save output device config
# ============================================================

if [ -z "$TERM" ] || [ "$TERM" = "dumb" ]; then
    for _t in xfce4-terminal lxterminal mate-terminal xterm gnome-terminal konsole qterminal; do
        command -v "$_t" &>/dev/null && break
    done
    case "$_t" in
        xfce4-terminal) exec "$_t" --disable-server -T "🔧 Audio Loopback Setup" -x bash "$0" "$@" ;;
        gnome-terminal) exec "$_t" --title "🔧 Audio Loopback Setup" -- bash "$0" "$@" ;;
        *)              exec "$_t" -T "🔧 Audio Loopback Setup" -e bash "$0" "$@" ;;
    esac
    exit $?
fi

trap 'ec=$?; echo ""; echo "Error (exit code: $ec). Press Enter to close..."; read _; exit 1' ERR

echo "╔══════════════════════════════════════════╗"
echo "║   Qji 奏在 — Audio Loopback Setup         ║"
echo "╚══════════════════════════════════════════╝"
echo ""

QJI_DIR="$HOME/qji"
mkdir -p "$QJI_DIR"

# ------------------------------------------------------------
# 1. Persist snd-aloop
#    (used as the receive end for gmediarender / AirPlay)
# ------------------------------------------------------------
step1() {
echo "▶ Checking ALSA loopback (snd-aloop)..."

if ! lsmod | grep -q snd_aloop; then
    sudo modprobe snd-aloop pcm_substreams=4
fi

if [ ! -f /etc/modules-load.d/qji-aloop.conf ]; then
    echo "snd-aloop" | sudo tee /etc/modules-load.d/qji-aloop.conf >/dev/null
    echo "options snd-aloop pcm_substreams=4" | sudo tee /etc/modprobe.d/qji-aloop.conf >/dev/null
    echo "  ✓ snd-aloop configured to load automatically at boot"
else
    echo "  ✓ Already configured"
fi
}
step1

echo ""

# ------------------------------------------------------------
# 2. Detect output device (USB DAC)
# ------------------------------------------------------------
echo "▶ Connected playback devices:"
echo ""
LC_ALL=C aplay -l | grep -E "^card" | sed 's/^/  /'
echo ""

LOOPBACK_CARD=$(LC_ALL=C aplay -l | grep -i "Loopback" | head -1 | sed -E 's/^card ([0-9]+).*/\1/')
DAC_CARD=$(LC_ALL=C aplay -l | grep -vi "Loopback\|HDMI\|bcm2835" | grep -E "^card" | head -1 | sed -E 's/^card ([0-9]+).*/\1/')

[ -z "$DAC_CARD" ]      && DAC_CARD=0
[ -z "$LOOPBACK_CARD" ] && LOOPBACK_CARD=1

echo "Suggested settings:"
echo "  Output (DAC)      : hw:${DAC_CARD},0"
echo "  Loopback (receive): hw:${LOOPBACK_CARD},0 / hw:${LOOPBACK_CARD},1"
echo ""
read -rp "DAC output card number [${DAC_CARD}]: " input_dac
DAC_CARD="${input_dac:-$DAC_CARD}"
read -rp "Loopback card number   [${LOOPBACK_CARD}]: " input_lb
LOOPBACK_CARD="${input_lb:-$LOOPBACK_CARD}"

cat > "$QJI_DIR/.audio_devices" << EOF
# Qji 奏在 — audio device config (generated by setup_audio_loopback.sh)
OUTPUT_DEVICE=hw:${DAC_CARD},0
LOOPBACK_IN=hw:${LOOPBACK_CARD},1,0
LOOPBACK_OUT=hw:${LOOPBACK_CARD},0,0
EOF

echo ""
echo "✅ Saved to ~/qji/.audio_devices:"
cat "$QJI_DIR/.audio_devices" | sed 's/^/   /'
echo ""
echo "  To change the output device (hw:X,0) later, edit"
echo "  ~/qji/.audio_devices or use the --device option in qji_en.py."
echo ""
read -rp "Press Enter to close..." _
